# Generated by Django 5.1.1 on 2024-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_category_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator')], max_length=225),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
