# Generated by Django 5.1.1 on 2024-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_rename_name_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator')], max_length=9, null=True),
        ),
    ]
